/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day7_package;

/**
 *
 * @author Asus
 */
public class GUI extends javax.swing.JPanel {

    String darbibaString =  ""; //Current calculation 
    String darbibaStringOld =  ""; //Previous calculation 
    boolean darbiba = false;
    
    public GUI() {
        initComponents();
        Lauks1.setText("0");
        Lauks2.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lauks1 = new javax.swing.JLabel();
        Poga_equals = new javax.swing.JButton();
        Poga0PlusMinus = new javax.swing.JButton();
        Poga0dot = new javax.swing.JButton();
        Poga00 = new javax.swing.JButton();
        Poga_minus = new javax.swing.JButton();
        Poga03 = new javax.swing.JButton();
        Poga02 = new javax.swing.JButton();
        Poga01 = new javax.swing.JButton();
        Poga_add = new javax.swing.JButton();
        Poga_multiply = new javax.swing.JButton();
        Poga09 = new javax.swing.JButton();
        Poga06 = new javax.swing.JButton();
        Poga05 = new javax.swing.JButton();
        Poga08 = new javax.swing.JButton();
        Poga07 = new javax.swing.JButton();
        Poga22 = new javax.swing.JButton();
        Poga_divide = new javax.swing.JButton();
        Poga_CE = new javax.swing.JButton();
        Poga_C = new javax.swing.JButton();
        Poga_squareRoot = new javax.swing.JButton();
        Lauks2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(320, 568));

        Lauks1.setBackground(new java.awt.Color(153, 153, 153));
        Lauks1.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        Lauks1.setForeground(new java.awt.Color(51, 51, 51));
        Lauks1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lauks1.setText("2950");
        Lauks1.setMaximumSize(new java.awt.Dimension(999, 999));
        Lauks1.setPreferredSize(new java.awt.Dimension(80, 80));

        Poga_equals.setBackground(new java.awt.Color(255, 153, 51));
        Poga_equals.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_equals.setForeground(new java.awt.Color(255, 255, 255));
        Poga_equals.setText("=");
        Poga_equals.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_equals.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_equals.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_equalsActionPerformed(evt);
            }
        });

        Poga0PlusMinus.setBackground(new java.awt.Color(204, 204, 204));
        Poga0PlusMinus.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga0PlusMinus.setForeground(new java.awt.Color(51, 51, 51));
        Poga0PlusMinus.setText("+/-");
        Poga0PlusMinus.setBorder(null);
        Poga0PlusMinus.setBorderPainted(false);
        Poga0PlusMinus.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga0PlusMinus.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga0PlusMinus.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga0PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga0PlusMinusActionPerformed(evt);
            }
        });

        Poga0dot.setBackground(new java.awt.Color(204, 204, 204));
        Poga0dot.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga0dot.setForeground(new java.awt.Color(51, 51, 51));
        Poga0dot.setText(".");
        Poga0dot.setBorder(null);
        Poga0dot.setBorderPainted(false);
        Poga0dot.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga0dot.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga0dot.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga0dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga0dotActionPerformed(evt);
            }
        });

        Poga00.setBackground(new java.awt.Color(204, 204, 204));
        Poga00.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga00.setForeground(new java.awt.Color(51, 51, 51));
        Poga00.setText("0");
        Poga00.setBorder(null);
        Poga00.setBorderPainted(false);
        Poga00.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga00.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga00.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga00ActionPerformed(evt);
            }
        });

        Poga_minus.setBackground(new java.awt.Color(200, 200, 200));
        Poga_minus.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_minus.setForeground(new java.awt.Color(153, 153, 153));
        Poga_minus.setText("-");
        Poga_minus.setBorder(null);
        Poga_minus.setBorderPainted(false);
        Poga_minus.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_minus.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_minus.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_minusActionPerformed(evt);
            }
        });

        Poga03.setBackground(new java.awt.Color(204, 204, 204));
        Poga03.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga03.setForeground(new java.awt.Color(51, 51, 51));
        Poga03.setText("3");
        Poga03.setBorder(null);
        Poga03.setBorderPainted(false);
        Poga03.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga03.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga03.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga03ActionPerformed(evt);
            }
        });

        Poga02.setBackground(new java.awt.Color(204, 204, 204));
        Poga02.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga02.setForeground(new java.awt.Color(51, 51, 51));
        Poga02.setText("2");
        Poga02.setBorder(null);
        Poga02.setBorderPainted(false);
        Poga02.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga02.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga02.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga02ActionPerformed(evt);
            }
        });

        Poga01.setBackground(new java.awt.Color(204, 204, 204));
        Poga01.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga01.setForeground(new java.awt.Color(51, 51, 51));
        Poga01.setText("1");
        Poga01.setBorder(null);
        Poga01.setBorderPainted(false);
        Poga01.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga01.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga01.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga01ActionPerformed(evt);
            }
        });

        Poga_add.setBackground(new java.awt.Color(200, 200, 200));
        Poga_add.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_add.setForeground(new java.awt.Color(153, 153, 153));
        Poga_add.setText("+");
        Poga_add.setBorder(null);
        Poga_add.setBorderPainted(false);
        Poga_add.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_add.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_add.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_addActionPerformed(evt);
            }
        });

        Poga_multiply.setBackground(new java.awt.Color(200, 200, 200));
        Poga_multiply.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_multiply.setForeground(new java.awt.Color(153, 153, 153));
        Poga_multiply.setText("x");
        Poga_multiply.setBorder(null);
        Poga_multiply.setBorderPainted(false);
        Poga_multiply.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_multiply.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_multiply.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_multiplyActionPerformed(evt);
            }
        });

        Poga09.setBackground(new java.awt.Color(204, 204, 204));
        Poga09.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga09.setForeground(new java.awt.Color(51, 51, 51));
        Poga09.setText("9");
        Poga09.setBorder(null);
        Poga09.setBorderPainted(false);
        Poga09.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga09.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga09.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga09ActionPerformed(evt);
            }
        });

        Poga06.setBackground(new java.awt.Color(204, 204, 204));
        Poga06.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga06.setForeground(new java.awt.Color(51, 51, 51));
        Poga06.setText("6");
        Poga06.setBorder(null);
        Poga06.setBorderPainted(false);
        Poga06.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga06.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga06.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga06ActionPerformed(evt);
            }
        });

        Poga05.setBackground(new java.awt.Color(204, 204, 204));
        Poga05.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga05.setForeground(new java.awt.Color(51, 51, 51));
        Poga05.setText("5");
        Poga05.setBorder(null);
        Poga05.setBorderPainted(false);
        Poga05.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga05.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga05.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga05ActionPerformed(evt);
            }
        });

        Poga08.setBackground(new java.awt.Color(204, 204, 204));
        Poga08.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga08.setForeground(new java.awt.Color(51, 51, 51));
        Poga08.setText("8");
        Poga08.setBorder(null);
        Poga08.setBorderPainted(false);
        Poga08.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga08.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga08.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga08ActionPerformed(evt);
            }
        });

        Poga07.setBackground(new java.awt.Color(204, 204, 204));
        Poga07.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga07.setForeground(new java.awt.Color(51, 51, 51));
        Poga07.setText("7");
        Poga07.setBorder(null);
        Poga07.setBorderPainted(false);
        Poga07.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga07.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga07.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga07ActionPerformed(evt);
            }
        });
        Poga07.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Poga07KeyPressed(evt);
            }
        });

        Poga22.setBackground(new java.awt.Color(204, 204, 204));
        Poga22.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga22.setForeground(new java.awt.Color(51, 51, 51));
        Poga22.setText("4");
        Poga22.setBorder(null);
        Poga22.setBorderPainted(false);
        Poga22.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga22.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga22.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga22ActionPerformed(evt);
            }
        });

        Poga_divide.setBackground(new java.awt.Color(200, 200, 200));
        Poga_divide.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_divide.setForeground(new java.awt.Color(153, 153, 153));
        Poga_divide.setText("÷");
        Poga_divide.setToolTipText("");
        Poga_divide.setBorder(null);
        Poga_divide.setBorderPainted(false);
        Poga_divide.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_divide.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_divide.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_divideActionPerformed(evt);
            }
        });

        Poga_CE.setBackground(new java.awt.Color(200, 200, 200));
        Poga_CE.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_CE.setForeground(new java.awt.Color(255, 153, 51));
        Poga_CE.setText("CE");
        Poga_CE.setBorder(null);
        Poga_CE.setBorderPainted(false);
        Poga_CE.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_CE.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_CE.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_CEActionPerformed(evt);
            }
        });

        Poga_C.setBackground(new java.awt.Color(200, 200, 200));
        Poga_C.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_C.setForeground(new java.awt.Color(255, 153, 51));
        Poga_C.setText("C");
        Poga_C.setBorder(null);
        Poga_C.setBorderPainted(false);
        Poga_C.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_C.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_C.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_CActionPerformed(evt);
            }
        });

        Poga_squareRoot.setBackground(new java.awt.Color(200, 200, 200));
        Poga_squareRoot.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Poga_squareRoot.setForeground(new java.awt.Color(153, 153, 153));
        Poga_squareRoot.setText("x2");
        Poga_squareRoot.setBorder(null);
        Poga_squareRoot.setBorderPainted(false);
        Poga_squareRoot.setMaximumSize(new java.awt.Dimension(57, 27));
        Poga_squareRoot.setMinimumSize(new java.awt.Dimension(57, 27));
        Poga_squareRoot.setPreferredSize(new java.awt.Dimension(80, 80));
        Poga_squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poga_squareRootActionPerformed(evt);
            }
        });

        Lauks2.setBackground(new java.awt.Color(153, 153, 153));
        Lauks2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Lauks2.setForeground(new java.awt.Color(153, 153, 153));
        Lauks2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lauks2.setText("30+20-15+");
        Lauks2.setMaximumSize(new java.awt.Dimension(999, 999));
        Lauks2.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Poga00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga0dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga0PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga_equals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Poga01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga_minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Poga22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Poga_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Poga07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Poga08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Poga_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Poga_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Poga09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(Poga_squareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(Poga_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lauks2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lauks1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(Poga_divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(Lauks2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lauks1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poga_divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga_squareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poga_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poga_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poga_minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poga_equals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga0PlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga0dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Poga00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Poga_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_equalsActionPerformed
        // Read fields and save result as variables:
        String lauks1temp = Lauks1.getText();
        String lauks2temp = Lauks2.getText();
        
        // If field1 contains anything but number   
        Aprekins aprekins = new Aprekins();
        if (lauks1temp.equals("+") || 
            lauks1temp.equals("-") || 
            lauks1temp.equals("x") || 
            lauks1temp.equals("^") || 
            lauks1temp.equals("/") || 
            lauks1temp.equals("%")){
            Lauks1.setText(lauks2temp);
            Lauks2.setText("");
            darbiba = false;
            darbibaString = "";
        }
        // If field2 is empty (i.e. first calculation)
        else if (lauks2temp.equals("")){
            Lauks1.setText(lauks1temp);
            darbiba = false;
            darbibaString = "";
        }
        // Perform calculation and read result
        else{
            double num1Int = Double.valueOf(lauks2temp);
            double num2Int = Double.valueOf(lauks1temp);
            Lauks1.setText(aprekins.aprekinsAll(darbibaString, num1Int, num2Int));
            Lauks2.setText("");
            darbiba = false;
            darbibaString = "";
        }
    }//GEN-LAST:event_Poga_equalsActionPerformed

    private void PogaSkaitlis(String numA){
        //Check if field1 contains anything but number, if so remove and write number.
        String currentText = Lauks1.getText();
        if(currentText.equals("0") || 
           currentText.equals("+") || 
           currentText.equals("-") || 
           currentText.equals("x") || 
           currentText.equals("^") || 
           currentText.equals("/") ||
           currentText.equals("%")){
        currentText = ""; 
        }
        if(numA.equals(".")&& currentText.contains(numA)){
        }
        else
        Lauks1.setText(currentText + numA);
        }
    
    private void PogaAprekins (String aprekins){        
        String lauks1temp = Lauks1.getText();
        String lauks2temp = Lauks2.getText();
        Aprekins aprekins2 = new Aprekins();
        String aprekinsTemp = "";
        boolean repeatedCalculation = false;
        
        if (lauks1temp.equals("0") || 
            lauks1temp.equals("+") || 
            lauks1temp.equals("-") || 
            lauks1temp.equals("x") || 
            lauks1temp.equals("^") || 
            lauks1temp.equals("/") || 
            lauks1temp.equals("%")){
            Lauks1.setText("");
            darbibaStringOld = aprekins;
            darbibaString = aprekins;
            repeatedCalculation = true;
        }
        else {
        darbibaStringOld = darbibaString; //saglabājam pagājušo matematisko funkciju
        darbibaString = aprekins; //jaunā aprēķina funkcija, kas tiek iedarbināta
        }
        
        //If Field1 equals nothing, then just save number from Field1 to Num1
        if(lauks2temp.equals(""))
            Lauks2.setText(lauks1temp);
        
        else if(repeatedCalculation == true){
            
        }

        else{
            double num1Int = Double.valueOf(lauks2temp); // pagājušo skaitļu summa
            double num2Int = Double.valueOf(lauks1temp); //jaunais skaitlis
            aprekinsTemp = aprekins2.aprekinsAll(darbibaStringOld, num1Int, num2Int);
            Lauks2.setText(aprekinsTemp);            
        }
        darbiba = true;
        Lauks1.setText(darbibaString);
        //reģistrē funkciju 
    }
    
    
    private void Poga00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga00ActionPerformed
        PogaSkaitlis("0");
    }//GEN-LAST:event_Poga00ActionPerformed

    private void Poga_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_minusActionPerformed
        PogaAprekins("-");
    }//GEN-LAST:event_Poga_minusActionPerformed

    private void Poga03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga03ActionPerformed
        PogaSkaitlis("3");
    }//GEN-LAST:event_Poga03ActionPerformed

    private void Poga02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga02ActionPerformed
        PogaSkaitlis("2");
    }//GEN-LAST:event_Poga02ActionPerformed

    private void Poga01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga01ActionPerformed
        PogaSkaitlis("1");
    }//GEN-LAST:event_Poga01ActionPerformed

    private void Poga_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_addActionPerformed
        PogaAprekins("+");
    }//GEN-LAST:event_Poga_addActionPerformed

    private void Poga_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_multiplyActionPerformed
        PogaAprekins("x");
    }//GEN-LAST:event_Poga_multiplyActionPerformed

    private void Poga09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga09ActionPerformed
        PogaSkaitlis("9");
    }//GEN-LAST:event_Poga09ActionPerformed

    private void Poga06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga06ActionPerformed
        PogaSkaitlis("6");
    }//GEN-LAST:event_Poga06ActionPerformed

    private void Poga05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga05ActionPerformed
        PogaSkaitlis("5");
    }//GEN-LAST:event_Poga05ActionPerformed

    private void Poga08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga08ActionPerformed
        PogaSkaitlis("8");
    }//GEN-LAST:event_Poga08ActionPerformed

    private void Poga07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga07ActionPerformed
        PogaSkaitlis("7");
    }//GEN-LAST:event_Poga07ActionPerformed

    private void Poga22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga22ActionPerformed
        PogaSkaitlis("4");
    }//GEN-LAST:event_Poga22ActionPerformed

    private void Poga_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_divideActionPerformed
        PogaAprekins("/");
    }//GEN-LAST:event_Poga_divideActionPerformed

    private void Poga_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_CEActionPerformed
            Lauks1.setText("0");
            darbiba = false;
    }//GEN-LAST:event_Poga_CEActionPerformed

    private void Poga_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_CActionPerformed
            Lauks1.setText("0");
            Lauks2.setText("");  
            darbiba = false;
    }//GEN-LAST:event_Poga_CActionPerformed

    private void Poga0PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga0PlusMinusActionPerformed
        String lauks1temp = Lauks1.getText();
        String lauks2temp = Lauks2.getText();
        
        if (lauks1temp.equals("0") || 
            lauks1temp.equals("+") || 
            lauks1temp.equals("-") || 
            lauks1temp.equals("x") || 
            lauks1temp.equals("^") || 
            lauks1temp.equals("/") || 
            lauks1temp.equals("%")){
        }
        else {
            if (lauks1temp.charAt(0) == '-'){
                lauks1temp = lauks1temp.replace("-","");
                Lauks1.setText(lauks1temp);
            }
            else{
                Lauks1.setText("-" + lauks1temp);
            }
                
        }
        
    }//GEN-LAST:event_Poga0PlusMinusActionPerformed

    private void Poga_squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga_squareRootActionPerformed
        PogaAprekins("^");
    }//GEN-LAST:event_Poga_squareRootActionPerformed

    private void Poga07KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Poga07KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Poga07KeyPressed

    private void Poga0dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poga0dotActionPerformed
        PogaSkaitlis(".");
    }//GEN-LAST:event_Poga0dotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lauks1;
    private javax.swing.JLabel Lauks2;
    private javax.swing.JButton Poga00;
    private javax.swing.JButton Poga01;
    private javax.swing.JButton Poga02;
    private javax.swing.JButton Poga03;
    private javax.swing.JButton Poga05;
    private javax.swing.JButton Poga06;
    private javax.swing.JButton Poga07;
    private javax.swing.JButton Poga08;
    private javax.swing.JButton Poga09;
    private javax.swing.JButton Poga0PlusMinus;
    private javax.swing.JButton Poga0dot;
    private javax.swing.JButton Poga22;
    private javax.swing.JButton Poga_C;
    private javax.swing.JButton Poga_CE;
    private javax.swing.JButton Poga_add;
    private javax.swing.JButton Poga_divide;
    private javax.swing.JButton Poga_equals;
    private javax.swing.JButton Poga_minus;
    private javax.swing.JButton Poga_multiply;
    private javax.swing.JButton Poga_squareRoot;
    // End of variables declaration//GEN-END:variables
}
